/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Multiplayer;

import Main.Main;
import Modes.ForceModePanel;
import Modes.Setup.ForceModeSetup;
import javax.swing.JFrame;

/**
 *
 * @author Ylope
 */
public class MultiplayerForce extends javax.swing.JPanel {
    int playerNum = 2;
    /**
     * Creates new form MultiplayerForce
     */
    public MultiplayerForce(int numPlayers) {
        initComponents();
        
        player1.setVisible(false);
        player2.setVisible(false);
        player3.setVisible(false);
        player4.setVisible(false);
        player5.setVisible(false);
        player6.setVisible(false);
        
        score1.setVisible(false);
        score2.setVisible(false);
        score3.setVisible(false);
        score4.setVisible(false);
        score5.setVisible(false);
        score6.setVisible(false);
        
        handi1.setVisible(false);
        handi2.setVisible(false);
        handi3.setVisible(false);
        handi4.setVisible(false);
        handi5.setVisible(false);
        handi6.setVisible(false);
        
         //Main.playerNum = numPlayers;
        
          if (Main.playerNum == 2) {
                player1.setVisible(true);
                player2.setVisible(true);
                score1.setVisible(true);
                score2.setVisible(true);
                handi1.setVisible(true);
                handi2.setVisible(true);
            }
            else if (Main.playerNum == 3) {
                player1.setVisible(true);
                player2.setVisible(true);
                player3.setVisible(true);
                score1.setVisible(true);
                score2.setVisible(true);
                score3.setVisible(true);
                handi1.setVisible(true);
                handi2.setVisible(true);
                handi3.setVisible(true);
            }
            else if (Main.playerNum == 4) {
                player1.setVisible(true);
                player2.setVisible(true);
                player3.setVisible(true);
                player4.setVisible(true);
                score1.setVisible(true);
                score2.setVisible(true);
                score3.setVisible(true);
                score4.setVisible(true);
                handi1.setVisible(true);
                handi2.setVisible(true);
                handi3.setVisible(true);
                handi4.setVisible(true);
            }
            else if (Main.playerNum == 5) {
                player1.setVisible(true);
                player2.setVisible(true);
                player3.setVisible(true);
                player4.setVisible(true);
                player5.setVisible(true);
                score1.setVisible(true);
                score2.setVisible(true);
                score3.setVisible(true);
                score4.setVisible(true);
                score5.setVisible(true);
                handi1.setVisible(true);
                handi2.setVisible(true);
                handi3.setVisible(true);
                handi4.setVisible(true);
                handi5.setVisible(true);
            }
            else if (Main.playerNum == 6) {
                player1.setVisible(true);
                player2.setVisible(true);
                player3.setVisible(true);
                player4.setVisible(true);
                player5.setVisible(true);
                player6.setVisible(true);
                score1.setVisible(true);
                score2.setVisible(true);
                score3.setVisible(true);
                score4.setVisible(true);
                score5.setVisible(true);
                score6.setVisible(true);
                handi1.setVisible(true);
                handi2.setVisible(true);
                handi3.setVisible(true);
                handi4.setVisible(true);
                handi5.setVisible(true);
                handi6.setVisible(true);
            }
  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleMulti = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        player1 = new javax.swing.JTextField();
        player3 = new javax.swing.JTextField();
        player4 = new javax.swing.JTextField();
        player5 = new javax.swing.JTextField();
        player6 = new javax.swing.JTextField();
        player2 = new javax.swing.JTextField();
        score1 = new javax.swing.JLabel();
        score3 = new javax.swing.JLabel();
        score4 = new javax.swing.JLabel();
        score5 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        score6 = new javax.swing.JLabel();
        handi1 = new javax.swing.JTextField();
        handi3 = new javax.swing.JTextField();
        handi4 = new javax.swing.JTextField();
        handi5 = new javax.swing.JTextField();
        handi6 = new javax.swing.JTextField();
        handi2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 55));
        setMaximumSize(new java.awt.Dimension(768, 1024));
        setMinimumSize(new java.awt.Dimension(768, 1024));

        jPanel1.setBackground(new java.awt.Color(0, 0, 55));
        jPanel1.setMaximumSize(new java.awt.Dimension(768, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(768, 1024));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TitleMulti.setBackground(new java.awt.Color(51, 51, 56));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("ComboCounter");

        javax.swing.GroupLayout TitleMultiLayout = new javax.swing.GroupLayout(TitleMulti);
        TitleMulti.setLayout(TitleMultiLayout);
        TitleMultiLayout.setHorizontalGroup(
            TitleMultiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleMultiLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
        );
        TitleMultiLayout.setVerticalGroup(
            TitleMultiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleMultiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Players");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Score");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Handicap");

        player1.setBackground(new java.awt.Color(0, 0, 55));
        player1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        player1.setForeground(new java.awt.Color(240, 240, 240));
        player1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player1.setText("Player 1");
        player1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        player1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player1KeyReleased(evt);
            }
        });

        player3.setBackground(new java.awt.Color(0, 0, 55));
        player3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        player3.setForeground(new java.awt.Color(240, 240, 240));
        player3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player3.setText("Player 3");
        player3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        player3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player3KeyReleased(evt);
            }
        });

        player4.setBackground(new java.awt.Color(0, 0, 55));
        player4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        player4.setForeground(new java.awt.Color(240, 240, 240));
        player4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player4.setText("Player 4");
        player4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        player4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player4KeyReleased(evt);
            }
        });

        player5.setBackground(new java.awt.Color(0, 0, 55));
        player5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        player5.setForeground(new java.awt.Color(240, 240, 240));
        player5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player5.setText("Player 5");
        player5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        player5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player5KeyReleased(evt);
            }
        });

        player6.setBackground(new java.awt.Color(0, 0, 55));
        player6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        player6.setForeground(new java.awt.Color(240, 240, 240));
        player6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player6.setText("Player 6");
        player6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        player6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player6KeyReleased(evt);
            }
        });

        player2.setBackground(new java.awt.Color(0, 0, 55));
        player2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        player2.setForeground(new java.awt.Color(240, 240, 240));
        player2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player2.setText("Player 2");
        player2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        player2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                player2KeyReleased(evt);
            }
        });

        score1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        score1.setForeground(new java.awt.Color(240, 240, 240));
        score1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        score1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                score1KeyReleased(evt);
            }
        });

        score3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        score3.setForeground(new java.awt.Color(240, 240, 240));
        score3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        score4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        score4.setForeground(new java.awt.Color(240, 240, 240));
        score4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        score5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        score5.setForeground(new java.awt.Color(240, 240, 240));
        score5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        score2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        score2.setForeground(new java.awt.Color(240, 240, 240));
        score2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        score6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        score6.setForeground(new java.awt.Color(240, 240, 240));
        score6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        handi1.setBackground(new java.awt.Color(0, 0, 55));
        handi1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        handi1.setForeground(new java.awt.Color(240, 240, 240));
        handi1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        handi1.setText("100");
        handi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        handi3.setBackground(new java.awt.Color(0, 0, 55));
        handi3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        handi3.setForeground(new java.awt.Color(240, 240, 240));
        handi3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        handi3.setText("100");
        handi3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        handi4.setBackground(new java.awt.Color(0, 0, 55));
        handi4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        handi4.setForeground(new java.awt.Color(240, 240, 240));
        handi4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        handi4.setText("100");
        handi4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        handi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handi4ActionPerformed(evt);
            }
        });

        handi5.setBackground(new java.awt.Color(0, 0, 55));
        handi5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        handi5.setForeground(new java.awt.Color(240, 240, 240));
        handi5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        handi5.setText("100");
        handi5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        handi6.setBackground(new java.awt.Color(0, 0, 55));
        handi6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        handi6.setForeground(new java.awt.Color(240, 240, 240));
        handi6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        handi6.setText("100");
        handi6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        handi2.setBackground(new java.awt.Color(0, 0, 55));
        handi2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        handi2.setForeground(new java.awt.Color(240, 240, 240));
        handi2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        handi2.setText("100");
        handi2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(TitleMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(player4)
                            .addComponent(player5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player6)
                            .addComponent(player2))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(score1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(handi1)
                            .addComponent(handi3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(handi4)
                            .addComponent(handi5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(handi6)
                            .addComponent(handi2))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TitleMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(score1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(handi1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(score2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(handi2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(score3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(handi3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(score4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(handi4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(score5, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(handi5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(score6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(handi6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void handi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handi4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Main.Frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //Frame.setResizable(false);
        Main.currentPlayer = 1;
        Main.Frame.setContentPane(new ForceModePanel(true, 500, 0, 0));
        Main.Frame.repaint();
        Main.Frame.revalidate();
        
        if (Main.doneFlag == true)
        {
            Main.done() ;
            return ;
        }
        Main.currentPlayer = 1;
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void player1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player1KeyReleased
        // TODO add your handling code here:
        Main.name1 = player1.getText();
    }//GEN-LAST:event_player1KeyReleased

    private void player2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player2KeyReleased
        // TODO add your handling code here:
        Main.name2 = player2.getText();
    }//GEN-LAST:event_player2KeyReleased

    private void player3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player3KeyReleased
        // TODO add your handling code here:
        Main.name3 = player3.getText();
    }//GEN-LAST:event_player3KeyReleased

    private void player4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player4KeyReleased
        // TODO add your handling code here:
        Main.name4 = player4.getText();
    }//GEN-LAST:event_player4KeyReleased

    private void player5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player5KeyReleased
        // TODO add your handling code here:
        Main.name5 = player5.getText();
    }//GEN-LAST:event_player5KeyReleased

    private void player6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player6KeyReleased
        // TODO add your handling code here:
        Main.name6 = player6.getText();
    }//GEN-LAST:event_player6KeyReleased

    private void score1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_score1KeyReleased
        // TODO add your handling code here:
        Main.score1 = score1.getText();
    }//GEN-LAST:event_score1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TitleMulti;
    private javax.swing.JTextField handi1;
    private javax.swing.JTextField handi2;
    private javax.swing.JTextField handi3;
    private javax.swing.JTextField handi4;
    private javax.swing.JTextField handi5;
    private javax.swing.JTextField handi6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JTextField player3;
    private javax.swing.JTextField player4;
    private javax.swing.JTextField player5;
    private javax.swing.JTextField player6;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel score3;
    private javax.swing.JLabel score4;
    private javax.swing.JLabel score5;
    private javax.swing.JLabel score6;
    // End of variables declaration//GEN-END:variables
}
