package Modes;

import Main.Activity;
import Main.Main;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * @author Jonathan Zamora
 */
public final class ActivityHistoryPanel extends javax.swing.JPanel {

    // Declaring vars

//    boolean countDown = true;
//    boolean paused = true;
//    boolean start;

    public ActivityHistoryPanel() {
        initComponents();
    }


    public void update() {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        jPanel1.setVisible(false);
        About_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Settings_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Profile_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Activity_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Feedback_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        jPanel2 = new javax.swing.JPanel();
        ComboCounterTitle = new javax.swing.JLabel();
        BackButton = new javax.swing.JLabel();
        SidebarButton = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ComboCounterTitle1 = new javax.swing.JLabel();
        BackButton1 = new javax.swing.JLabel();
        SidebarButton1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonALLModes = new javax.swing.JButton();
        forceMode = new javax.swing.JButton();
        timeMode = new javax.swing.JButton();
        comboMode = new javax.swing.JButton();
        punchMode = new javax.swing.JButton();
        strenghMode = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 55));
        jPanel1.setMaximumSize(new java.awt.Dimension(768, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(768, 1024));
        jPanel1.setPreferredSize(new java.awt.Dimension(768, 1024));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBackground(new java.awt.Color(0, 0, 55));
        setMaximumSize(new java.awt.Dimension(768, 1024));
        setMinimumSize(new java.awt.Dimension(768, 1024));
        setPreferredSize(new java.awt.Dimension(768, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBar.setBackground(new java.awt.Color(51, 51, 56));
        SideBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 5, 0, new java.awt.Color(0, 0, 0)));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        About_Button.setBackground(new java.awt.Color(51, 51, 56));
        About_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        About_Button.setForeground(new java.awt.Color(240, 240, 240));
        About_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aboutIcon.png"))); // NOI18N
        About_Button.setText(" About");
        About_Button.setBorder(null);
        About_Button.setContentAreaFilled(false);
        About_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                About_ButtonMouseClicked(evt);
            }
        });
        SideBar.add(About_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 60));

        Settings_Button.setBackground(new java.awt.Color(51, 51, 56));
        Settings_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Settings_Button.setForeground(new java.awt.Color(240, 240, 240));
        Settings_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settingsIcon.png"))); // NOI18N
        Settings_Button.setText(" Settings");
        Settings_Button.setBorder(null);
        Settings_Button.setContentAreaFilled(false);
        Settings_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Settings_Button.setFocusPainted(false);
        Settings_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Settings_ButtonMouseClicked(evt);
            }
        });
        SideBar.add(Settings_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 60));

        Profile_Button.setBackground(new java.awt.Color(51, 51, 56));
        Profile_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Profile_Button.setForeground(new java.awt.Color(240, 240, 240));
        Profile_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileIcon.png"))); // NOI18N
        Profile_Button.setText(" Profile");
        Profile_Button.setBorder(null);
        Profile_Button.setContentAreaFilled(false);
        Profile_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Profile_ButtonMouseClicked(evt);
            }
        });
        SideBar.add(Profile_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 60));

        Activity_Button.setBackground(new java.awt.Color(51, 51, 56));
        Activity_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Activity_Button.setForeground(new java.awt.Color(240, 240, 240));
        Activity_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/activityIcon.png"))); // NOI18N
        Activity_Button.setText(" Activity");
        Activity_Button.setBorder(null);
        Activity_Button.setContentAreaFilled(false);
        Activity_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Activity_ButtonMouseClicked(evt);
            }
        });
        SideBar.add(Activity_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 60));

        Feedback_Button.setBackground(new java.awt.Color(51, 51, 56));
        Feedback_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Feedback_Button.setForeground(new java.awt.Color(240, 240, 240));
        Feedback_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/feedbackIcon.png"))); // NOI18N
        Feedback_Button.setText(" Feedback");
        Feedback_Button.setBorder(null);
        Feedback_Button.setContentAreaFilled(false);
        Feedback_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Feedback_ButtonMouseClicked(evt);
            }
        });
        SideBar.add(Feedback_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 180, 60));

        add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 250, 530));

        jPanel2.setBackground(new java.awt.Color(51, 51, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboCounterTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ComboCounterTitle.setForeground(new java.awt.Color(240, 240, 240));
        ComboCounterTitle.setText("Activity History");
        jPanel2.add(ComboCounterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backIcon.png"))); // NOI18N
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        jPanel2.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        SidebarButton.setBackground(new java.awt.Color(51, 51, 56));
        SidebarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SidebarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menuIcon.png"))); // NOI18N
        SidebarButton.setOpaque(true);
        SidebarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarButtonMouseClicked(evt);
            }
        });
        jPanel2.add(SidebarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 60, 55));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 80));

        jPanel4.setBackground(new java.awt.Color(51, 51, 56));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboCounterTitle1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ComboCounterTitle1.setForeground(new java.awt.Color(240, 240, 240));
        ComboCounterTitle1.setText("ComboCounter");
        jPanel4.add(ComboCounterTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        BackButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backIcon.png"))); // NOI18N
        BackButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButton1MouseClicked(evt);
            }
        });
        jPanel4.add(BackButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        SidebarButton1.setBackground(new java.awt.Color(51, 51, 56));
        SidebarButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SidebarButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menuIcon.png"))); // NOI18N
        SidebarButton1.setOpaque(true);
        SidebarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarButton1MouseClicked(evt);
            }
        });
        jPanel4.add(SidebarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 60, 55));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 80));

        jScrollPane2.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 55));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea1PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 650, 810));

        jButtonALLModes.setText("All");
        jButtonALLModes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonALLModesMouseClicked(evt);
            }
        });
        jButtonALLModes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonALLModesActionPerformed(evt);
            }
        });
        add(jButtonALLModes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        forceMode.setText("Force Mode");
        forceMode.setToolTipText("");
        forceMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forceModeMouseClicked(evt);
            }
        });
        forceMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forceModeActionPerformed(evt);
            }
        });
        add(forceMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        timeMode.setText("Time Mode");
        timeMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeModeMouseClicked(evt);
            }
        });
        add(timeMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        comboMode.setText("Combo Mode");
        comboMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboModeMouseClicked(evt);
            }
        });
        add(comboMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        punchMode.setText("Punch Mode");
        punchMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                punchModeMouseClicked(evt);
            }
        });
        add(punchMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        strenghMode.setText("Strengh Mode");
        strenghMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                strenghModeMouseClicked(evt);
            }
        });
        add(strenghMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        Main.setup(3);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void SidebarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarButtonMouseClicked
        if (Main.sidebarOpen == false) {
            SideBar.setVisible(true);
            Main.sidebarOpen = true;
        } else if (Main.sidebarOpen == true) {
            SideBar.setVisible(false);
            Main.sidebarOpen = false;
        }
    }//GEN-LAST:event_SidebarButtonMouseClicked

    private void Feedback_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Feedback_ButtonMouseClicked
        /*start = false;
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? (Progress is not saved)","Exit", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION)
        // Page to transition to*/
    }//GEN-LAST:event_Feedback_ButtonMouseClicked

    private void Activity_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Activity_ButtonMouseClicked
        Main.ActivityHistory();
        /*start = false;
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? (Progress is not saved)","Exit", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION)
        // Page to transition to*/
    }//GEN-LAST:event_Activity_ButtonMouseClicked

    private void Profile_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_ButtonMouseClicked
        /*start = false;
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? (Progress is not saved)","Exit", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION)
        // Page to transition to*/
    }//GEN-LAST:event_Profile_ButtonMouseClicked

    private void Settings_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_ButtonMouseClicked
        boolean start = false;
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? (Progress is not saved)", "Exit", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION)
            Main.transitionToPage(3);
    }//GEN-LAST:event_Settings_ButtonMouseClicked

    private void About_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_About_ButtonMouseClicked
        /*start = false;
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? (Progress is not saved)","Exit", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION)
        // Page to transition to*/
    }//GEN-LAST:event_About_ButtonMouseClicked

    private void SidebarButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SidebarButton1MouseClicked

    private void BackButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButton1MouseClicked

    private void jTextArea1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea1PropertyChange
        try {
            jTextArea1.setText(Main.db.DisplayForceHistory(Main.username) + Main.db.DisplayTimeHistory(Main.username) 
                    + Main.db.DisplayPunchHistory(Main.username) + Main.db.DisplayStrengthHistory(Main.username) +
                            Main.db.DisplayComboHistory(Main.username));
        } catch (SQLException ex) {
            Logger.getLogger(ActivityHistoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButtonALLModes.setBackground(Color.lightGray);
        
        forceMode.setBackground(new Color(240,240,240));
        timeMode.setBackground(new Color(240,240,240));
        strenghMode.setBackground(new Color(240,240,240));
        punchMode.setBackground(new Color(240,240,240));
        comboMode.setBackground(new Color(240,240,240));
        //Main.db.
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1PropertyChange

    private void jButtonALLModesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonALLModesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonALLModesActionPerformed

    private void forceModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forceModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forceModeActionPerformed

    private void jButtonALLModesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonALLModesMouseClicked
        try {
            // TODO add your handling code here:
            jTextArea1.setText(Main.db.DisplayForceHistory(Main.username) + Main.db.DisplayTimeHistory(Main.username) 
                    + Main.db.DisplayPunchHistory(Main.username) + Main.db.DisplayStrengthHistory(Main.username) +
                            Main.db.DisplayComboHistory(Main.username));
        } catch (SQLException ex) {
            Logger.getLogger(ActivityHistoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButtonALLModes.setBackground(Color.lightGray);
        
        forceMode.setBackground(new Color(240,240,240));
        timeMode.setBackground(new Color(240,240,240));
        strenghMode.setBackground(new Color(240,240,240));
        punchMode.setBackground(new Color(240,240,240));
        comboMode.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_jButtonALLModesMouseClicked

    private void forceModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forceModeMouseClicked
        try {
            jTextArea1.setText(Main.db.DisplayForceHistory(Main.username));
        } catch (SQLException ex) {
            Logger.getLogger(ActivityHistoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        forceMode.setBackground(Color.lightGray);
        
        jButtonALLModes.setBackground(new Color(240,240,240));
        timeMode.setBackground(new Color(240,240,240));
        strenghMode.setBackground(new Color(240,240,240));
        punchMode.setBackground(new Color(240,240,240));
        comboMode.setBackground(new Color(240,240,240));
        // TODO add your handling code here:
    }//GEN-LAST:event_forceModeMouseClicked

    private void timeModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeModeMouseClicked
        jTextArea1.setText(Main.db.DisplayTimeHistory(Main.username));
        timeMode.setBackground(Color.lightGray);
        
        jButtonALLModes.setBackground(new Color(240,240,240));
        forceMode.setBackground(new Color(240,240,240));
        strenghMode.setBackground(new Color(240,240,240));
        punchMode.setBackground(new Color(240,240,240));
        comboMode.setBackground(new Color(240,240,240));
        // TODO add your handling code here:
    }//GEN-LAST:event_timeModeMouseClicked

    private void strenghModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strenghModeMouseClicked
        // TODO add your handling code here:
        jTextArea1.setText(Main.db.DisplayStrengthHistory(Main.username));
        strenghMode.setBackground(Color.lightGray);
        
        jButtonALLModes.setBackground(new Color(240,240,240));
        forceMode.setBackground(new Color(240,240,240));
        timeMode.setBackground(new Color(240,240,240));
        punchMode.setBackground(new Color(240,240,240));
        comboMode.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_strenghModeMouseClicked

    private void punchModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_punchModeMouseClicked
        // TODO add your handling code here:
        jTextArea1.setText(Main.db.DisplayPunchHistory(Main.username));
        punchMode.setBackground(Color.lightGray);
        
        jButtonALLModes.setBackground(new Color(240,240,240));
        forceMode.setBackground(new Color(240,240,240));
        timeMode.setBackground(new Color(240,240,240));
        strenghMode.setBackground(new Color(240,240,240));
        comboMode.setBackground(new Color(240,240,240));
        
    }//GEN-LAST:event_punchModeMouseClicked

    private void comboModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboModeMouseClicked
        // TODO add your handling code here:
        jTextArea1.setText(Main.db.DisplayComboHistory(Main.username));
        comboMode.setBackground(Color.lightGray);
        
        jButtonALLModes.setBackground(new Color(240,240,240));
        forceMode.setBackground(new Color(240,240,240));
        timeMode.setBackground(new Color(240,240,240));
        strenghMode.setBackground(new Color(240,240,240));
        punchMode.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_comboModeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_Button;
    private javax.swing.JButton Activity_Button;
    private javax.swing.JLabel BackButton;
    private javax.swing.JLabel BackButton1;
    private javax.swing.JLabel ComboCounterTitle;
    private javax.swing.JLabel ComboCounterTitle1;
    private javax.swing.JButton Feedback_Button;
    private javax.swing.JButton Profile_Button;
    private javax.swing.JButton Settings_Button;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel SidebarButton;
    private javax.swing.JLabel SidebarButton1;
    private javax.swing.JButton comboMode;
    private javax.swing.JButton forceMode;
    private javax.swing.JButton jButtonALLModes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton punchMode;
    private javax.swing.JButton strenghMode;
    private javax.swing.JButton timeMode;
    // End of variables declaration//GEN-END:variables
}
