package Main;

import javax.swing.JFrame;
/**
 * @author Jonathan Zamora
 */
public class FirstPage extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public FirstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginButton = new javax.swing.JButton();
        GetStartedButton = new javax.swing.JButton();
        ComboCounterTitle = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        PunchingBagImage = new javax.swing.JLabel();
        QuoteLabel2 = new javax.swing.JLabel();
        QuoteLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 55));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginButton.setBackground(new java.awt.Color(0, 0, 55));
        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(240, 240, 240));
        LoginButton.setText("Login");
        LoginButton.setBorder(GetStartedButton.getBorder());
        LoginButton.setBorderPainted(false);
        LoginButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 110, 30));

        GetStartedButton.setBackground(new java.awt.Color(51, 51, 51));
        GetStartedButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        GetStartedButton.setForeground(new java.awt.Color(240, 240, 240));
        GetStartedButton.setText("Get Started");
        GetStartedButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        GetStartedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GetStartedButtonMouseClicked(evt);
            }
        });
        add(GetStartedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 250, 70));

        ComboCounterTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ComboCounterTitle.setForeground(new java.awt.Color(0, 122, 203));
        ComboCounterTitle.setText("ComboCounter");
        add(ComboCounterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label.setForeground(new java.awt.Color(240, 240, 240));
        Label.setText("Already have an account?");
        add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 280, 30));

        PunchingBagImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PunchingBagImage.png"))); // NOI18N
        add(PunchingBagImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 250, 270));

        QuoteLabel2.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        QuoteLabel2.setText("No Matter How Small\"");
        add(QuoteLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 900, 250, 50));

        QuoteLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        QuoteLabel1.setText("\"Progress is Progress");
        add(QuoteLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 860, 250, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        Main.Frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Main.Frame.setContentPane(new LoginPanel());
        Main.Frame.setSize(768,1024);
        Main.Frame.setResizable(false);
        Main.Frame.repaint();
        Main.Frame.revalidate();
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void GetStartedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetStartedButtonMouseClicked
        Main.Frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Main.Frame.setContentPane(new RegisterPanel());
        Main.Frame.setSize(768,1024);
        Main.Frame.setResizable(false);
        Main.Frame.repaint();
        Main.Frame.revalidate();
    }//GEN-LAST:event_GetStartedButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ComboCounterTitle;
    private javax.swing.JButton GetStartedButton;
    private javax.swing.JLabel Label;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel PunchingBagImage;
    private javax.swing.JLabel QuoteLabel1;
    private javax.swing.JLabel QuoteLabel2;
    // End of variables declaration//GEN-END:variables
}
