package Modes.Setup;

import Main.Main;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 * @author Jonathan Zamora
 */
public class ForceModeSetup extends javax.swing.JPanel {
    // Declaring vars
    int timerMin;
    int timerSec;
    int forceGoal = 500;
    int numPlayers = 6;
    boolean countDown = true;
    boolean multiplayer = false;
        
    /**
     * Creates new form homePagePanel
     */
    Timer timer;
    public ForceModeSetup() 
    {
        initComponents();       
        Main.playerNum = 2;
       
        // Setting Plus and Minus state
        SideBar.setVisible(false);
        ForceGoalMinus.setVisible(false);
        ForceGoalPlus.setVisible(false);
        NumOfPlayers.setVisible(false);
        NumOfPlayersText.setVisible(false);
        NumPlayersPlus.setVisible(false);
        NumPlayersMinus.setVisible(false);
        Training_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }
    
    public void invisible()
    {
        ForceGoalMinus.setVisible(false);
        ForceGoalPlus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setVisible(false);
        About_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Settings_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Profile_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Activity_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Feedback_Button = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        SideBar = new javax.swing.JPanel();
        jPanel1.setVisible(false);
        About_Button1 = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Settings_Button1 = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Profile_Button1 = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Activity_Button1 = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Feedback_Button1 = new javax.swing.JButton();
        About_Button.setOpaque(false);
        About_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        jPanel2 = new javax.swing.JPanel();
        SidebarButton = new javax.swing.JLabel();
        ComboCounterTitle = new javax.swing.JLabel();
        PunchChallengeButton = new javax.swing.JLabel();
        ForceModeButton = new javax.swing.JLabel();
        TimedModeButton = new javax.swing.JLabel();
        ComboModeButton = new javax.swing.JLabel();
        StrengthModeButton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ForceGoal = new javax.swing.JLabel();
        ForceGoalPlus = new javax.swing.JLabel();
        ForceGoalMinus = new javax.swing.JLabel();
        Training_Button = new javax.swing.JLabel();
        NumOfPlayersText = new javax.swing.JLabel();
        NumOfPlayers = new javax.swing.JLabel();
        NumPlayersPlus = new javax.swing.JLabel();
        NumPlayersMinus = new javax.swing.JLabel();
        Competition_Button = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 51, 56));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 5, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        About_Button.setBackground(new java.awt.Color(51, 51, 56));
        About_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        About_Button.setForeground(new java.awt.Color(240, 240, 240));
        About_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aboutIcon.png"))); // NOI18N
        About_Button.setText(" About");
        About_Button.setBorder(null);
        About_Button.setContentAreaFilled(false);
        About_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                About_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(About_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 60));

        Settings_Button.setBackground(new java.awt.Color(51, 51, 56));
        Settings_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Settings_Button.setForeground(new java.awt.Color(240, 240, 240));
        Settings_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settingsIcon.png"))); // NOI18N
        Settings_Button.setText(" Settings");
        Settings_Button.setBorder(null);
        Settings_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Settings_Button.setFocusPainted(false);
        Settings_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Settings_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(Settings_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 60));

        Profile_Button.setBackground(new java.awt.Color(51, 51, 56));
        Profile_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Profile_Button.setForeground(new java.awt.Color(240, 240, 240));
        Profile_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileIcon.png"))); // NOI18N
        Profile_Button.setText(" Profile");
        Profile_Button.setBorder(null);
        Profile_Button.setContentAreaFilled(false);
        Profile_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Profile_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(Profile_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 60));

        Activity_Button.setBackground(new java.awt.Color(51, 51, 56));
        Activity_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Activity_Button.setForeground(new java.awt.Color(240, 240, 240));
        Activity_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/activityIcon.png"))); // NOI18N
        Activity_Button.setText(" Activity");
        Activity_Button.setBorder(null);
        Activity_Button.setContentAreaFilled(false);
        Activity_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Activity_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(Activity_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 60));

        Feedback_Button.setBackground(new java.awt.Color(51, 51, 56));
        Feedback_Button.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Feedback_Button.setForeground(new java.awt.Color(240, 240, 240));
        Feedback_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/feedbackIcon.png"))); // NOI18N
        Feedback_Button.setText(" Feedback");
        Feedback_Button.setBorder(null);
        Feedback_Button.setContentAreaFilled(false);
        Feedback_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Feedback_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(Feedback_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 180, 60));

        setBackground(new java.awt.Color(0, 0, 55));
        setMaximumSize(new java.awt.Dimension(768, 1024));
        setMinimumSize(new java.awt.Dimension(768, 1024));
        setPreferredSize(new java.awt.Dimension(768, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBar.setBackground(new java.awt.Color(51, 51, 56));
        SideBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 5, 0, new java.awt.Color(0, 0, 0)));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        About_Button1.setBackground(new java.awt.Color(51, 51, 56));
        About_Button1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        About_Button1.setForeground(new java.awt.Color(240, 240, 240));
        About_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aboutIcon.png"))); // NOI18N
        About_Button1.setText(" About");
        About_Button1.setBorder(null);
        About_Button1.setContentAreaFilled(false);
        About_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                About_Button1MouseClicked(evt);
            }
        });
        SideBar.add(About_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 60));

        Settings_Button1.setBackground(new java.awt.Color(51, 51, 56));
        Settings_Button1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Settings_Button1.setForeground(new java.awt.Color(240, 240, 240));
        Settings_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settingsIcon.png"))); // NOI18N
        Settings_Button1.setText(" Settings");
        Settings_Button1.setBorder(null);
        Settings_Button1.setContentAreaFilled(false);
        Settings_Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Settings_Button1.setFocusPainted(false);
        Settings_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Settings_Button1MouseClicked(evt);
            }
        });
        SideBar.add(Settings_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 60));

        Profile_Button1.setBackground(new java.awt.Color(51, 51, 56));
        Profile_Button1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Profile_Button1.setForeground(new java.awt.Color(240, 240, 240));
        Profile_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileIcon.png"))); // NOI18N
        Profile_Button1.setText(" Profile");
        Profile_Button1.setBorder(null);
        Profile_Button1.setContentAreaFilled(false);
        Profile_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Profile_Button1MouseClicked(evt);
            }
        });
        SideBar.add(Profile_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 60));

        Activity_Button1.setBackground(new java.awt.Color(51, 51, 56));
        Activity_Button1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Activity_Button1.setForeground(new java.awt.Color(240, 240, 240));
        Activity_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/activityIcon.png"))); // NOI18N
        Activity_Button1.setText(" Activity");
        Activity_Button1.setBorder(null);
        Activity_Button1.setContentAreaFilled(false);
        Activity_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Activity_Button1MouseClicked(evt);
            }
        });
        SideBar.add(Activity_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 60));

        Feedback_Button1.setBackground(new java.awt.Color(51, 51, 56));
        Feedback_Button1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Feedback_Button1.setForeground(new java.awt.Color(240, 240, 240));
        Feedback_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/feedbackIcon.png"))); // NOI18N
        Feedback_Button1.setText(" Feedback");
        Feedback_Button1.setBorder(null);
        Feedback_Button1.setContentAreaFilled(false);
        Feedback_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Feedback_Button1MouseClicked(evt);
            }
        });
        SideBar.add(Feedback_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 180, 60));

        add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 80, 250, 530));

        jPanel2.setBackground(new java.awt.Color(51, 51, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidebarButton.setBackground(new java.awt.Color(51, 51, 56));
        SidebarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SidebarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menuIcon.png"))); // NOI18N
        SidebarButton.setOpaque(true);
        SidebarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarButtonMouseClicked(evt);
            }
        });
        jPanel2.add(SidebarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 60, 55));

        ComboCounterTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ComboCounterTitle.setForeground(new java.awt.Color(240, 240, 240));
        ComboCounterTitle.setText("ComboCounter");
        jPanel2.add(ComboCounterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 80));

        PunchChallengeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emptyCircleIcon.png"))); // NOI18N
        add(PunchChallengeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 30, 30));

        ForceModeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/filledCircleIcon.png"))); // NOI18N
        add(ForceModeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 30, 30));

        TimedModeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emptyCircleIcon.png"))); // NOI18N
        TimedModeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimedModeButtonMouseClicked(evt);
            }
        });
        add(TimedModeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 30, 30));

        ComboModeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emptyCircleIcon.png"))); // NOI18N
        ComboModeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboModeButtonMouseClicked(evt);
            }
        });
        add(ComboModeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 30, 30));

        StrengthModeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emptyCircleIcon.png"))); // NOI18N
        StrengthModeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StrengthModeButtonMouseClicked(evt);
            }
        });
        add(StrengthModeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 30, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Force Goal");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 180, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Force Mode");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 230, 50));

        ForceGoal.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ForceGoal.setForeground(new java.awt.Color(240, 240, 240));
        ForceGoal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForceGoal.setText("500");
        ForceGoal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForceGoalMouseClicked(evt);
            }
        });
        add(ForceGoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 190, 40));

        ForceGoalPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plusIcon.png"))); // NOI18N
        ForceGoalPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForceGoalPlusMouseClicked(evt);
            }
        });
        add(ForceGoalPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, 40));

        ForceGoalMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minusIcon.png"))); // NOI18N
        ForceGoalMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForceGoalMinusMouseClicked(evt);
            }
        });
        add(ForceGoalMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, 40));

        Training_Button.setBackground(new java.awt.Color(51, 51, 56));
        Training_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Training_Button.setForeground(new java.awt.Color(240, 240, 240));
        Training_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Training_Button.setText("Training");
        Training_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Training_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Training_ButtonMouseClicked(evt);
            }
        });
        add(Training_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 210, 60));

        NumOfPlayersText.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        NumOfPlayersText.setForeground(new java.awt.Color(240, 240, 240));
        NumOfPlayersText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumOfPlayersText.setText("# of Players:");
        add(NumOfPlayersText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 680, 220, 50));

        NumOfPlayers.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        NumOfPlayers.setForeground(new java.awt.Color(240, 240, 240));
        NumOfPlayers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumOfPlayers.setText("2");
        add(NumOfPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 60, 50));

        NumPlayersPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circlePlusIcon.png"))); // NOI18N
        NumPlayersPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NumPlayersPlusMouseClicked(evt);
            }
        });
        add(NumPlayersPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, -1, 40));

        NumPlayersMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circleMinusIcon.png"))); // NOI18N
        NumPlayersMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NumPlayersMinusMouseClicked(evt);
            }
        });
        add(NumPlayersMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, -1, 40));

        Competition_Button.setBackground(new java.awt.Color(51, 51, 56));
        Competition_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Competition_Button.setForeground(new java.awt.Color(240, 240, 240));
        Competition_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Competition_Button.setText("Competition");
        Competition_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Competition_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Competition_ButtonMouseClicked(evt);
            }
        });
        add(Competition_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 210, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Player Setting");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 260, 50));

        StartButton.setBackground(new java.awt.Color(51, 51, 56));
        StartButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        StartButton.setForeground(new java.awt.Color(240, 240, 240));
        StartButton.setText("Start");
        StartButton.setContentAreaFilled(false);
        StartButton.setFocusPainted(false);
        StartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartButtonMouseClicked(evt);
            }
        });
        add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 790, 180, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void SidebarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarButtonMouseClicked
        if (Main.sidebarOpen == false)
        {
            SideBar.setVisible(true) ;
            Main.sidebarOpen = true ;
        }
        else if (Main.sidebarOpen == true)
        {
            SideBar.setVisible(false);
            Main.sidebarOpen = false ;
        }
    }//GEN-LAST:event_SidebarButtonMouseClicked

    private void About_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_About_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_About_ButtonMouseClicked

    private void Settings_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_ButtonMouseClicked
        Main.transitionToPage(3);
    }//GEN-LAST:event_Settings_ButtonMouseClicked

    private void Profile_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_ButtonMouseClicked

    private void Activity_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Activity_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Activity_ButtonMouseClicked

    private void Feedback_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Feedback_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Feedback_ButtonMouseClicked

    private void ForceGoalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForceGoalMouseClicked
        ForceGoalMinus.setVisible(true);
        ForceGoalPlus.setVisible(true);
        ActionListener taskPerformer = new ActionListener() 
        {
            public void actionPerformed(ActionEvent evt)
            {
                ForceGoalMinus.setVisible(false);
                ForceGoalPlus.setVisible(false);
            }
        };
        Timer timer = new Timer(7000, taskPerformer);
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_ForceGoalMouseClicked

    private void ForceGoalPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForceGoalPlusMouseClicked
        if (forceGoal < 3000)
        {
            forceGoal += 500;
        }
        else if (forceGoal < 10000)
        {
            forceGoal += 1000;
        }
        else if (forceGoal < 100000)
        {
            forceGoal += 5000;
        }
        ForceGoal.setText(String.format("%,d", forceGoal));
    }//GEN-LAST:event_ForceGoalPlusMouseClicked

    private void ForceGoalMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForceGoalMinusMouseClicked
        if (forceGoal <= 3000)
        {
            forceGoal -= 500;
        }
        else if (forceGoal <= 10000)
        {
            forceGoal -= 1000;
        }
        else if (forceGoal <= 100000)
        {
            forceGoal -= 5000;
        }
        String frcGoal = String.valueOf(forceGoal);
        ForceGoal.setText(frcGoal);
    }//GEN-LAST:event_ForceGoalMinusMouseClicked

    private void TimedModeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimedModeButtonMouseClicked
        Main.setup(3);
    }//GEN-LAST:event_TimedModeButtonMouseClicked

    private void Training_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Training_ButtonMouseClicked
        if (multiplayer == true)
        {
            multiplayer = false ;
            Training_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
            Competition_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

            // Removes # of Players Visibility
            NumOfPlayersText.setVisible(false);
            NumOfPlayers.setVisible(false);
            NumPlayersPlus.setVisible(false);
            NumPlayersMinus.setVisible(false);
        }
    }//GEN-LAST:event_Training_ButtonMouseClicked

    private void NumPlayersPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumPlayersPlusMouseClicked
        if (Main.playerNum < 10)
        {
            Main.playerNum++;
            String num = String.valueOf(Main.playerNum);
            NumOfPlayers.setText(num);
        }
    }//GEN-LAST:event_NumPlayersPlusMouseClicked

    private void NumPlayersMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumPlayersMinusMouseClicked
        if (Main.playerNum > 2)
        {
            Main.playerNum--;
            String num = String.valueOf(Main.playerNum);
            NumOfPlayers.setText(num);
        }
    }//GEN-LAST:event_NumPlayersMinusMouseClicked

    private void Competition_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Competition_ButtonMouseClicked
        if (multiplayer == false)
        {
            multiplayer = true ;
            Competition_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
            Training_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

            // Visiblity to add players
            NumOfPlayersText.setVisible(true);
            NumOfPlayers.setVisible(true);
            NumPlayersPlus.setVisible(true);
            NumPlayersMinus.setVisible(true);

        }
    }//GEN-LAST:event_Competition_ButtonMouseClicked

    private void StartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartButtonMouseClicked
        if (multiplayer == false)
        Main.createForceMode(multiplayer, forceGoal, timerMin, timerSec);
        else 
        {
            Main.multiplayer(numPlayers);
        }
    }//GEN-LAST:event_StartButtonMouseClicked

    private void About_Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_About_Button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_About_Button1MouseClicked

    private void Settings_Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_Button1MouseClicked
        Main.transitionToPage(3);
    }//GEN-LAST:event_Settings_Button1MouseClicked

    private void Profile_Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_Button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_Button1MouseClicked

    private void Activity_Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Activity_Button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Activity_Button1MouseClicked

    private void Feedback_Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Feedback_Button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Feedback_Button1MouseClicked

    private void StrengthModeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StrengthModeButtonMouseClicked
        // TODO add your handling code here:
        Main.setup(4);
    }//GEN-LAST:event_StrengthModeButtonMouseClicked

    private void ComboModeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboModeButtonMouseClicked
        // TODO add your handling code here:
        Main.setup(1);
    }//GEN-LAST:event_ComboModeButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_Button;
    private javax.swing.JButton About_Button1;
    private javax.swing.JButton Activity_Button;
    private javax.swing.JButton Activity_Button1;
    private javax.swing.JLabel ComboCounterTitle;
    private javax.swing.JLabel ComboModeButton;
    private javax.swing.JLabel Competition_Button;
    private javax.swing.JButton Feedback_Button;
    private javax.swing.JButton Feedback_Button1;
    private javax.swing.JLabel ForceGoal;
    private javax.swing.JLabel ForceGoalMinus;
    private javax.swing.JLabel ForceGoalPlus;
    private javax.swing.JLabel ForceModeButton;
    private javax.swing.JLabel NumOfPlayers;
    private javax.swing.JLabel NumOfPlayersText;
    private javax.swing.JLabel NumPlayersMinus;
    private javax.swing.JLabel NumPlayersPlus;
    private javax.swing.JButton Profile_Button;
    private javax.swing.JButton Profile_Button1;
    private javax.swing.JLabel PunchChallengeButton;
    private javax.swing.JButton Settings_Button;
    private javax.swing.JButton Settings_Button1;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel SidebarButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel StrengthModeButton;
    private javax.swing.JLabel TimedModeButton;
    private javax.swing.JLabel Training_Button;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
